//! The scale of Chabrier's high-mass branch (plan 15, P15.T4), which `galaxy::imf::Chabrier`
//! multiplies its power law above 1 M☉ by.
//!
//! @generated by hyperion-fit 0.1.0, task `chabrier` revision 1. Do not edit.
//! inputs-sha256: ba78b5c24c758488b801da0ac940b383e36caca25147dc04bc02b0cfc65bc030
//! manifest: crates/hyperion-fit/manifests/chabrier.toml
//! data: none
//! sim-fingerprint: 390d7c9fa85e4754ab9b3cff86d152e9e79aeadd63ee33d3bdb2cb23a5db18e7
//! since-generator-version: 14
//! source: the volume-complete census within 20 pc (Kirkpatrick et al. 2024, ApJS 271, 55, table
//!   4, tallied; ruling 138); Chabrier (2003, PASP 115, 763); plan 11's multiplicity model
//! acceptance: s = 0.9201 (1σ 0.8507–0.9927; under the IFMRs of Cummings 2018 0.8957, El-Badry
//!   2018 0.9352); over primaries below 8 M☉: band shares A–D 67.7, 12.0, 16.8, 3.45% against
//!   66.5, 12.8, 17.8, 2.85%, misses of -0.73, +1.19, +1.15, -1.53 Poisson errors, χ² 5.62 on 2
//!   dof (passes); all stars below 0.5 M☉ 69.84% in 67.8–71.0% (passes); local mid-plane mean per
//!   system in stars and white dwarfs 0.5517 M☉ in 0.54–0.60 (passes). Reported: the
//!   all-inclusive local mean 0.6115 M☉, of which neutron stars and black holes 0.0530; the
//!   primaries' mean present mass 0.4027 M☉ against the census's 0.437
//!
//! Fitted (P15.T4.b, ruling 138): the multinomial maximum-likelihood scale of the 20 pc
//! census's primaries in bands A–D, the model's shares renormalised over 0.08–8 M☉.

/// The factor on Chabrier's (2003) power law above 1 M☉, dimensionless: the fit to
/// the census's 1,491 / 288 / 400 / 64 primaries in bands A–D (Kirkpatrick et al.
/// 2024, table 4, tallied; ruling 138).
pub const HIGH_MASS_BRANCH_SCALE: f64 = 0.920_102_355_171_049_4;
