//! The direct companions' period correction (plan 11, ruling 81.3): the factors under
//! which the periods that survive rejection follow Moe and Di Stefano's law.
//!
//! @generated by hyperion-fit 0.1.0, task `period_correction` revision 0. Do not edit.
//! inputs-sha256: 1a89abede0e9e8f006b95278258df215e3beafd1a3519f32c49aa9b389734c44
//! manifest: crates/hyperion-fit/manifests/period_correction.toml
//! data: none
//! sim-fingerprint: 9c7b2984c75da79cbd0564e6dc46aef65baca92775c31c39dab6936ab45e2c6b
//! since-generator-version: 14
//! source: Moe and Di Stefano (2017, ApJS 230, 15), eqs. 20–23 and Table 13; Mardling and Aarseth
//!   (2001, MNRAS 321, 398) for the rejection
//! acceptance: after 12 iterations over 20000 systems a row, the worst bin's relative miss of its
//!   share before the last update: 0.0012 at 3.5 M☉ (28.87% of tries rejected, 7 of 16683 direct
//!   companions dropped); 0.0007 at 7 M☉ (53.70% of tries rejected, 58 of 25887 direct companions
//!   dropped); 0.0008 at 12 M☉ (70.87% of tries rejected, 127 of 31813 direct companions
//!   dropped); 0.0010 at 28 M☉ (72.78% of tries rejected, 241 of 41918 direct companions dropped)
//!
//! Inputs: 12 iterations of `c ← c × target ÷ measured` from a table of ones, over
//! 20000 systems at each row's mass (`stellar::multiplicity::period_fit::record`: the Sun-like
//! point of the Milky Way fixture, free, first attempt); the targets are the bin shares of Moe
//! and Di Stefano's eqs. 20–23 law, normalised over log₁₀(P ÷ 1 d) = 0.2–8.

/// The factors on the direct companions' period law, a row for each primary mass of
/// `CORRECTION_MASSES` and a column for each period bin 0.2–1, 1–2, …, 7–8.
pub const PERIOD_CORRECTION: [[f64; 8]; 4] = [
    [
        0.780_872_618_560_769_2,
        0.966_048_399_154_477_8,
        1.013_897_455_043_749_2,
        1.090_300_449_722_920_3,
        1.170_775_225_837_900_3,
        1.030_600_264_255_199_2,
        1.003_434_895_938_529_3,
        0.834_563_137_282_256,
    ],
    [
        0.685_243_626_531_210_3,
        0.890_772_589_650_734_5,
        1.117_038_367_887_934_8,
        1.250_523_206_437_705_9,
        1.265_747_420_643_988,
        1.090_184_576_871_431_6,
        0.869_856_232_364_042_9,
        0.646_712_489_854_865_6,
    ],
    [
        0.831_679_968_832_094_4,
        1.036_602_822_680_819,
        1.239_671_596_886_513_3,
        1.263_042_894_862_293_2,
        1.290_403_762_592_081_7,
        1.011_404_504_934_788_6,
        0.725_356_137_104_443_7,
        0.505_535_430_663_235_8,
    ],
    [
        0.835_084_939_777_147,
        1.163_873_721_711_636_8,
        1.347_414_327_905_358_3,
        1.384_561_235_964_265,
        1.236_772_606_458_386_8,
        0.980_443_424_879_334_1,
        0.637_119_248_431_967_8,
        0.443_606_023_844_028_3,
    ],
];
