/**
 * The Sun's light in the atmosphere's three channels (plan R05, Design note 16, R05.T12.a): its
 * spectral irradiance at the channels' wavelengths and Bruneton's factors that turn spectral
 * samples into linear Rec. 709 luminance.
 *
 * @remarks
 * Generated by `apps/hyperion/scripts/solarFactors.mjs` (`src/tools/solarFactors.ts`) from the ASTM
 * E-490-00a AM0 spectrum and the CIE 1931 2° matching functions; that tool's header names each
 * input's source, version and SHA-256. The inputs are not committed (R05.T12.d, ruled
 * 2026-10-02). Solar spectral irradiance values derived from ASTM E490-00a(2019), obtained from the
 * U.S. DOE National Laboratory of the Rockies (NLR, formerly NREL); credit DOE/NLR/Alliance. The
 * matching functions: CIE 2019, DOI 10.25039/CIE.DS.xvudnb9b, CC BY-SA 4.0 (see `NOTICE`).
 * R08.T6.d replaces the factors with R07's `starIlluminance` and keeps this file as a 1%
 * luminance check.
 *
 * The tables hold radiance per unit solar spectral irradiance at each channel's wavelength. A
 * table value T_c becomes Rec. 709 luminance as T_c × {@link skyLuminanceScale}()_c; the Sun's own
 * disc as {@link sunIlluminanceRgb}()_c ÷ its solid angle.
 */

import { illuminanceLx } from "../photometry/magnitude";
import type { Rgb } from "../photometry/toneCurve";

/**
 * E-490's spectral irradiance at 1 au at 680, 550 and 440 nm, W m⁻² nm⁻¹ (generated).
 *
 * @remarks
 * A point sample of a spectrum with absorption lines, not a bin mean; in k_c × E(λ_c) it cancels,
 * so the Sun and the sky do not depend on it.
 */
export const SOLAR_SPECTRAL_IRRADIANCE_W_M2_NM: Rgb = [1.495, 1.8785, 1.769];

/**
 * Bruneton's spectral-radiance-to-luminance factors for the Sun's own light (λ power 0), lm nm W⁻¹
 * (generated). k_c × E(λ_c) is the channel's share of the Sun's Rec. 709 illuminance, lx.
 */
export const SUN_SPECTRAL_TO_LUMINANCE: Rgb = [98_071.88, 69_274.18, 71_060.92];

/**
 * Bruneton's spectral-radiance-to-luminance factors for sky light (λ power −3), lm nm W⁻¹
 * (generated).
 */
export const SKY_SPECTRAL_TO_LUMINANCE: Rgb = [114_566.5, 70_725.83, 69_767.03];

/**
 * E-490's photopic illuminance at 1 au, lx: 683 lm W⁻¹ × ∫ ȳ E dλ over 360–830 nm (generated).
 *
 * @remarks
 * 4% above the 1.28 × 10⁵ lx that R02's V-magnitude photometry gives for V = −26.76;
 * {@link sunIlluminanceRgb} is scaled to the latter, so that the Sun in the atmosphere and the Sun
 * as a star agree.
 */
export const E490_ILLUMINANCE_LX = 133_318.3;

/** The Sun's apparent V magnitude at 1 au: −26.76 (Willmer, ApJS 236 (2018) 47). */
export const SUN_APPARENT_V = -26.76;

/**
 * The luminance (Y) of a linear Rec. 709 colour: 0.2126729, 0.7151522, 0.072175, the sRGB
 * primaries' Y row with D65 white XYZ (0.95047, 1, 1.08883) to seven figures (Lindbloom), as
 * Filament's `ColorSpaceUtils.h` and `toneCurve.ts` carry it.
 */
export function rec709Luminance(rgb: Rgb): number {
  return 0.212_672_9 * rgb[0] + 0.715_152_2 * rgb[1] + 0.072_175 * rgb[2];
}

const UNSCALED_SUN: Rgb = [
  SUN_SPECTRAL_TO_LUMINANCE[0] * SOLAR_SPECTRAL_IRRADIANCE_W_M2_NM[0],
  SUN_SPECTRAL_TO_LUMINANCE[1] * SOLAR_SPECTRAL_IRRADIANCE_W_M2_NM[1],
  SUN_SPECTRAL_TO_LUMINANCE[2] * SOLAR_SPECTRAL_IRRADIANCE_W_M2_NM[2],
];

const SUN_SCALE = illuminanceLx(SUN_APPARENT_V) / rec709Luminance(UNSCALED_SUN);

const SUN_RGB_LX: Rgb = [
  UNSCALED_SUN[0] * SUN_SCALE,
  UNSCALED_SUN[1] * SUN_SCALE,
  UNSCALED_SUN[2] * SUN_SCALE,
];

const SKY_SCALE: Rgb = [
  SKY_SPECTRAL_TO_LUMINANCE[0] * SOLAR_SPECTRAL_IRRADIANCE_W_M2_NM[0] * SUN_SCALE,
  SKY_SPECTRAL_TO_LUMINANCE[1] * SOLAR_SPECTRAL_IRRADIANCE_W_M2_NM[1] * SUN_SCALE,
  SKY_SPECTRAL_TO_LUMINANCE[2] * SOLAR_SPECTRAL_IRRADIANCE_W_M2_NM[2] * SUN_SCALE,
];

/**
 * The Sun's top-of-atmosphere illuminance at 1 au per Rec. 709 channel, lx, whose luminance is
 * R02's 1.28 × 10⁵ lx for V = −26.76.
 */
export function sunIlluminanceRgb(): Rgb {
  return SUN_RGB_LX;
}

/**
 * The factor per channel from a table's radiance per unit solar spectral irradiance to Rec. 709
 * luminance at 1 au, lx: k_sky,c × E(λ_c), scaled as {@link sunIlluminanceRgb} is. A table value in
 * sr⁻¹ times this factor is a luminance in cd m⁻².
 */
export function skyLuminanceScale(): Rgb {
  return SKY_SCALE;
}
