//! Wire protocol shared by the HYPERION server and its clients.
//!
//! Every message is a JSON object discriminated by a `type` field, and requests carry a body
//! discriminated by `kind` (see [`ClientMessage`] and [`RequestBody`]). This crate holds wire types
//! only: the server converts the simulation's types to and from them, and nothing here depends on
//! the simulation. The one behaviour it has is the text form of 64-bit values, which cross the wire
//! as 16 lowercase hexadecimal digits because a JSON number cannot carry a `u64` into JavaScript.
//!
//! The TypeScript bindings in `packages/protocol/src/generated` are generated from these types by
//! `ts-rs` when running `cargo test` (`just gen-protocol`); never edit them by hand.

mod envelope;
mod galaxy;
mod primitives;
#[cfg(test)]
pub(crate) mod testing;
mod universe;

pub use envelope::{
    ClientMessage, ErrorCode, REQUEST_KINDS, RequestBody, RequestError, RequestId, ResponseBody,
    ServerMessage,
};
pub use galaxy::{
    Census, DensityMap, DensityMapRequest, GalaxyParameters, GalaxyParametersRequest, LayerCensus,
    LayerStatus, MapPopulation, MapView, MassLayer, Parameter, ParameterGroup, ParameterOrigin,
    ParameterValue, Population, SystemRecord, SystemsInRange, SystemsInRangeRequest, Unit,
};
pub use primitives::{
    GalacticPosition, ParseHex64Error, SeedHex, SystemIdHex, UniverseIdHex, UniverseTime,
};
pub use universe::{
    CreateUniverseRequest, OpenUniverseRequest, UniverseInfo, UniverseList, UniverseStatus,
};

/// The version of the wire protocol, sent in every `welcome`.
///
/// A client compares it with its own and refuses a server that differs. Adding a request kind or
/// an optional field does not bump it, since an older server answers the new kind with
/// `unsupported`; removing or changing a message, a field or a string does. Version 2 added the
/// request convention, which a version 1 server cannot serve at all.
pub const PROTOCOL_VERSION: u32 = 2;

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    /// Where ts-rs writes bindings: `TS_RS_EXPORT_DIR` at run time, else its default.
    fn export_dir() -> PathBuf {
        std::env::var_os("TS_RS_EXPORT_DIR")
            .map_or_else(|| PathBuf::from("./bindings"), PathBuf::from)
    }

    /// Writes `ProtocolVersion.ts` beside the generated types, so that the client's constant comes
    /// from this one. The name puts it under the `export_bindings` filter of `just gen-protocol`.
    #[test]
    fn export_bindings_protocol_version() {
        let dir = export_dir();
        std::fs::create_dir_all(&dir).unwrap();
        let text = format!(
            "// This file was generated from `hyperion_protocol::PROTOCOL_VERSION` by \
             `just gen-protocol`.\n\
             // Do not edit this file manually.\n\
             \n\
             /**\n \
             * The version of the wire protocol, sent in every `welcome`. A server that sends\n \
             * another version cannot serve this client.\n \
             */\n\
             export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n"
        );
        std::fs::write(dir.join("ProtocolVersion.ts"), text).unwrap();
    }

    #[test]
    fn protocol_version_is_two() {
        assert_eq!(PROTOCOL_VERSION, 2);
    }
}
