//! The Rust source emitter: a table's header, its items and the file they go into (plan 15, P15.T2
//! and Design notes 4, 5 and 10).
//!
//! A table is Rust source under `crates/hyperion-sim/src/tables/`, because the sim does no I/O. Its
//! file opens with a module doc whose first paragraph is a one-sentence summary, followed by the
//! header of Design note 5, one `key: value` line each, and then any notes the task adds:
//!
//! ```text
//! //! <one-sentence summary>.
//! //!
//! //! @generated by hyperion-fit <crate version>, task `<name>` revision <n>. Do not edit.
//! //! inputs-sha256: <64 hex digits>
//! //! manifest: crates/hyperion-fit/manifests/<name>.toml
//! //! data: `<dataset>@<sha256 prefix>`, ...          (or `none`)
//! //! sim-fingerprint: <64 hex digits>                 (or `none`)
//! //! since-generator-version: <n>
//! //! source: <citations the fit was made against>
//! //! acceptance: <the measured figures of the acceptance test>
//! ```
//!
//! A scratch stand-in has `@provisional by <tool or plan task>` in place of the `@generated` line
//! and needs only `since-generator-version` and `source`; a hand-entered constant file has
//! `@static`. A long value continues on lines indented by two more spaces.
//!
//! The *body* is everything after the header's comment lines: the items. Its SHA-256 is what the
//! lock file records, so a header rewritten to this grammar leaves the body, and so the table,
//! unchanged. Where two tasks fill one file, each task's header and items sit between its own pair
//! of marker comments, `// @begin-table <name>` and `// @end-table <name>`, with the header in `//`
//! comments, and the emitter rewrites only that block ([`Placement::Block`]).
//!
//! Floats are written as the shortest decimal that reads back to the same `f64`, digits grouped in
//! threes with `_` on both sides of the point (Clippy's `unreadable_literal`), exponent kept
//! ([`literal`]). Arrays carry `#[rustfmt::skip]`, one row a line, so that `cargo fmt --check`
//! accepts them however long a row is.

use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::manifest::{LockEntry, LockFile, ReadLockError};

/// The marker opening one task's block in a file two tasks share.
pub const BLOCK_BEGIN: &str = "// @begin-table ";

/// The marker closing one task's block.
pub const BLOCK_END: &str = "// @end-table ";

/// The marker comments around `tables::MANIFEST` in the sim's `tables/mod.rs`.
pub const MANIFEST_BEGIN: &str =
    "// @begin-manifest: written by hyperion-fit from tables.lock. Do not edit.";

/// The marker closing `tables::MANIFEST`.
pub const MANIFEST_END: &str = "// @end-manifest";

/// `value` as a Rust float literal: the shortest decimal that reads back to the same `f64`, with
/// its digits grouped in threes as Clippy asks. A negative value keeps its sign in front of the
/// grouped digits, and an exponent is kept.
///
/// # Examples
///
/// ```
/// use hyperion_fit::emit::literal;
///
/// assert_eq!(literal(1_234.567_8), "1_234.567_8");
/// assert_eq!(literal(1.234_567e-7), "1.234_567e-7");
/// assert_eq!(literal(-2.0), "-2.0");
/// ```
#[must_use]
pub fn literal(value: f64) -> String {
    let shortest = format!("{value:?}");
    let (sign, unsigned) = match shortest.strip_prefix('-') {
        Some(rest) => ("-", rest),
        None => ("", shortest.as_str()),
    };
    let (mantissa, exponent) = match unsigned.split_once('e') {
        Some((m, e)) => (m, Some(e)),
        None => (unsigned, None),
    };
    let (whole, fraction) = mantissa.split_once('.').unwrap_or((mantissa, "0"));
    let mut out = String::from(sign);
    let digits: Vec<char> = whole.chars().collect();
    for (i, c) in digits.iter().enumerate() {
        if i > 0 && (digits.len() - i).is_multiple_of(3) {
            out.push('_');
        }
        out.push(*c);
    }
    out.push('.');
    for (i, c) in fraction.chars().enumerate() {
        if i > 0 && i.is_multiple_of(3) {
            out.push('_');
        }
        out.push(c);
    }
    if let Some(e) = exponent {
        out.push('e');
        out.push_str(e);
    }
    out
}

/// A finite `value` as a literal, or [`EmitTableError::NonFinite`] naming the item.
fn finite_literal(item: &str, value: f64) -> Result<String, EmitTableError> {
    if value.is_finite() {
        Ok(literal(value))
    } else {
        Err(EmitTableError::NonFinite {
            item: item.to_owned(),
        })
    }
}

/// The SHA-256 of `bytes` as 64 lowercase hex digits.
#[must_use]
pub fn sha256_hex(bytes: &[u8]) -> String {
    hex(&Sha256::digest(bytes))
}

/// `bytes` as lowercase hex digits.
#[must_use]
pub(crate) fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(2 * bytes.len());
    for b in bytes {
        let _ = write!(out, "{b:02x}");
    }
    out
}

/// What kind of table a header declares.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum HeaderKind {
    /// The output of a fit: `@generated by hyperion-fit <version>, task `<name>` revision <n>.`
    Generated,
    /// A scratch stand-in: `@provisional by <by>.` The text says which tool or plan task made it.
    Provisional {
        /// The tool or plan task that made it, for instance "P15.T4.a".
        by: String,
    },
    /// A hand-entered constant file that is not a fit: `@static.`
    Static,
}

/// A table's header (Design note 5), as written and as read back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
pub struct Header {
    /// `@generated`, `@provisional` or `@static`; `None` only while being built.
    pub kind: Option<HeaderKind>,
    /// The task that wrote it, if a task did.
    pub task: Option<String>,
    /// The task's revision, if a task wrote it.
    pub revision: Option<u32>,
    /// The version of `hyperion-fit` that wrote it, if it did.
    pub tool_version: Option<String>,
    /// `inputs-sha256`, 64 hex digits.
    pub inputs_sha256: Option<String>,
    /// `manifest`, the manifest's path relative to the repository.
    pub manifest: Option<String>,
    /// `data`, each dataset's name and the prefix of its recorded hash; `Some(empty)` is `none`.
    pub data: Option<Vec<(String, String)>>,
    /// `sim-fingerprint`, 64 hex digits; `Some(None)` is `none`.
    pub sim_fingerprint: Option<Option<String>>,
    /// `since-generator-version`.
    pub since_generator_version: Option<u32>,
    /// `source`.
    pub source: Option<String>,
    /// `acceptance`.
    pub acceptance: Option<String>,
}

/// The number of hex digits of a dataset's hash that the `data` line quotes.
pub const DATA_HASH_PREFIX: usize = 12;

impl Header {
    /// The header's key lines, without comment prefixes, continuation lines indented by two
    /// spaces.
    ///
    /// # Errors
    ///
    /// [`EmitTableError::Header`] if the kind or `since-generator-version` is missing, a generated
    /// table lacks its task, revision, inputs hash, manifest, data or fingerprint, or `source` is
    /// missing.
    pub fn lines(&self) -> Result<Vec<String>, EmitTableError> {
        let missing = |what: &str| EmitTableError::Header(format!("the header has no {what}"));
        let mut lines = Vec::new();
        let tool = || {
            format!(
                "hyperion-fit {}, task `{}` revision {}",
                self.tool_version
                    .as_deref()
                    .unwrap_or(env!("CARGO_PKG_VERSION")),
                self.task.as_deref().unwrap_or_default(),
                self.revision.unwrap_or_default()
            )
        };
        match self.kind.as_ref().ok_or_else(|| missing("kind"))? {
            HeaderKind::Generated => {
                if self.task.is_none() || self.revision.is_none() {
                    return Err(missing("task and revision"));
                }
                lines.push(format!("@generated by {}. Do not edit.", tool()));
            }
            HeaderKind::Provisional { by } => {
                if self.task.is_some() {
                    lines.push(format!("@provisional by {} ({by}). Do not edit.", tool()));
                } else {
                    lines.push(format!("@provisional by {by}. Do not edit."));
                }
            }
            HeaderKind::Static => lines.push("@static.".to_owned()),
        }
        let generated = self.kind == Some(HeaderKind::Generated);
        if let Some(hash) = &self.inputs_sha256 {
            lines.push(format!("inputs-sha256: {hash}"));
        } else if generated {
            return Err(missing("inputs-sha256"));
        }
        if let Some(manifest) = &self.manifest {
            lines.push(format!("manifest: {manifest}"));
        } else if generated {
            return Err(missing("manifest"));
        }
        match &self.data {
            Some(data) if data.is_empty() => lines.push("data: none".to_owned()),
            Some(data) => {
                // In backticks, which rustdoc's lint on bare identifiers asks for.
                let list: Vec<String> = data.iter().map(|(n, h)| format!("`{n}@{h}`")).collect();
                lines.push(format!("data: {}", list.join(", ")));
            }
            None if generated => return Err(missing("data")),
            None => {}
        }
        match &self.sim_fingerprint {
            Some(Some(hash)) => lines.push(format!("sim-fingerprint: {hash}")),
            Some(None) => lines.push("sim-fingerprint: none".to_owned()),
            None if generated => return Err(missing("sim-fingerprint")),
            None => {}
        }
        let since = self
            .since_generator_version
            .ok_or_else(|| missing("since-generator-version"))?;
        lines.push(format!("since-generator-version: {since}"));
        let source = self.source.as_ref().ok_or_else(|| missing("source"))?;
        push_wrapped(&mut lines, "source: ", source);
        if let Some(acceptance) = &self.acceptance {
            push_wrapped(&mut lines, "acceptance: ", acceptance);
        }
        Ok(lines)
    }

    /// Reads a header back from its key lines, without comment prefixes.
    ///
    /// # Errors
    ///
    /// [`EmitTableError::Header`] for a line that is not in the grammar, a key given twice, or a
    /// header that [`lines`](Self::lines) would not write.
    pub fn parse<'a>(lines: impl IntoIterator<Item = &'a str>) -> Result<Self, EmitTableError> {
        let bad = |why: String| EmitTableError::Header(why);
        let mut joined: Vec<String> = Vec::new();
        for line in lines {
            if let Some(rest) = line.strip_prefix("  ") {
                let last = joined
                    .last_mut()
                    .ok_or_else(|| bad("the header opens with a continuation line".to_owned()))?;
                last.push(' ');
                last.push_str(rest.trim_start());
            } else {
                joined.push(line.to_owned());
            }
        }
        let mut header = Self::default();
        let mut keys = joined.iter();
        let first = keys
            .next()
            .ok_or_else(|| bad("the header is empty".to_owned()))?;
        header.parse_kind(first)?;
        for line in keys {
            let (key, value) = line
                .split_once(": ")
                .ok_or_else(|| bad(format!("`{line}` is not `key: value`")))?;
            let twice = || bad(format!("`{key}` is given twice"));
            match key {
                "inputs-sha256" => {
                    check_hex(value)?;
                    replace_once(&mut header.inputs_sha256, value.to_owned())
                        .map_err(|()| twice())?;
                }
                "manifest" => {
                    replace_once(&mut header.manifest, value.to_owned()).map_err(|()| twice())?;
                }
                "data" => {
                    let data = if value == "none" {
                        Vec::new()
                    } else {
                        value
                            .split(", ")
                            .map(|d| {
                                let d = d.trim_matches('`');
                                d.split_once('@')
                                    .map(|(n, h)| (n.to_owned(), h.to_owned()))
                                    .ok_or_else(|| bad(format!("`{d}` is not `dataset@hash`")))
                            })
                            .collect::<Result<_, _>>()?
                    };
                    replace_once(&mut header.data, data).map_err(|()| twice())?;
                }
                "sim-fingerprint" => {
                    let hash = if value == "none" {
                        None
                    } else {
                        check_hex(value)?;
                        Some(value.to_owned())
                    };
                    replace_once(&mut header.sim_fingerprint, hash).map_err(|()| twice())?;
                }
                "since-generator-version" => {
                    let since = value
                        .parse()
                        .map_err(|_| bad(format!("`{value}` is not a generator version")))?;
                    replace_once(&mut header.since_generator_version, since)
                        .map_err(|()| twice())?;
                }
                "source" => {
                    replace_once(&mut header.source, value.to_owned()).map_err(|()| twice())?;
                }
                "acceptance" => {
                    replace_once(&mut header.acceptance, value.to_owned()).map_err(|()| twice())?;
                }
                other => return Err(bad(format!("`{other}` is not a header key"))),
            }
        }
        header.lines()?;
        Ok(header)
    }

    /// Reads the first line: the kind, and the tool, task and revision that made the table.
    fn parse_kind(&mut self, line: &str) -> Result<(), EmitTableError> {
        let bad = || EmitTableError::Header(format!("`{line}` opens no header"));
        if line == "@static." {
            self.kind = Some(HeaderKind::Static);
            return Ok(());
        }
        let (generated, rest) = if let Some(rest) = line.strip_prefix("@generated by ") {
            (true, rest)
        } else if let Some(rest) = line.strip_prefix("@provisional by ") {
            (false, rest)
        } else {
            return Err(bad());
        };
        let rest = rest.strip_suffix(". Do not edit.").ok_or_else(bad)?;
        let (tool, by) = if generated {
            (Some(rest), None)
        } else if let Some(tool) = rest.strip_prefix("hyperion-fit ") {
            let (tool, by) = tool.rsplit_once(" (").ok_or_else(bad)?;
            (Some(tool), Some(by.strip_suffix(')').ok_or_else(bad)?))
        } else {
            (None, Some(rest))
        };
        if let Some(tool) = tool {
            let tool = tool.strip_prefix("hyperion-fit ").unwrap_or(tool);
            let (version, task) = tool.split_once(", task `").ok_or_else(bad)?;
            let (task, revision) = task.split_once("` revision ").ok_or_else(bad)?;
            self.tool_version = Some(version.to_owned());
            self.task = Some(task.to_owned());
            self.revision = Some(revision.parse().map_err(|_| bad())?);
        }
        self.kind = Some(match by {
            None => HeaderKind::Generated,
            Some(by) => HeaderKind::Provisional { by: by.to_owned() },
        });
        Ok(())
    }
}

/// Sets `slot` unless it is already set.
fn replace_once<T>(slot: &mut Option<T>, value: T) -> Result<(), ()> {
    if slot.is_some() {
        return Err(());
    }
    *slot = Some(value);
    Ok(())
}

/// Checks that `value` is 64 lowercase hex digits.
fn check_hex(value: &str) -> Result<(), EmitTableError> {
    if value.len() == 64
        && value
            .bytes()
            .all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
    {
        Ok(())
    } else {
        Err(EmitTableError::Header(format!(
            "`{value}` is not 64 hex digits"
        )))
    }
}

/// The widest a header line's text runs before it continues on the next, in characters.
const WRAP: usize = 94;

/// Pushes `key` and `value` as one line, continued on lines indented by two spaces where it would
/// run past [`WRAP`] characters.
fn push_wrapped(lines: &mut Vec<String>, key: &str, value: &str) {
    let mut line = key.to_owned();
    let mut fresh = true;
    for word in value.split(' ') {
        if !fresh && line.chars().count() + 1 + word.chars().count() > WRAP {
            lines.push(line);
            line = format!("  {word}");
        } else {
            if !fresh {
                line.push(' ');
            }
            line.push_str(word);
        }
        fresh = false;
    }
    lines.push(line);
}

/// One item of a table.
#[derive(Debug, Clone, PartialEq)]
pub enum TableItem {
    /// `pub const NAME: f64 = value;`
    Scalar {
        /// The constant's name.
        name: String,
        /// Its `///` comment, with its unit and source, one entry a line.
        doc: Vec<String>,
        /// Its value.
        value: f64,
    },
    /// `pub const NAME: [f64; N] = [...];`, one value a line.
    Array {
        /// The constant's name.
        name: String,
        /// Its `///` comment.
        doc: Vec<String>,
        /// Its values.
        values: Vec<f64>,
    },
    /// `pub const NAME: [(f64, ...); N] = [...];`, one tuple a line.
    Tuples {
        /// The constant's name.
        name: String,
        /// Its `///` comment.
        doc: Vec<String>,
        /// The tuples, all of one length of at least two.
        rows: Vec<Vec<f64>>,
    },
    /// `pub const NAME: [Type; N] = [...];`, one struct literal with named `f64` fields a line.
    Structs {
        /// The constant's name.
        name: String,
        /// Its `///` comment.
        doc: Vec<String>,
        /// The struct's type, as the table file names it.
        type_name: String,
        /// The fields' names.
        fields: Vec<String>,
        /// The values, one row per struct, one value per field.
        rows: Vec<Vec<f64>>,
    },
    /// `pub const NAME: [[f64; M]; N] = [...];`, one inner array a line.
    Nested {
        /// The constant's name.
        name: String,
        /// Its `///` comment.
        doc: Vec<String>,
        /// The rows, all of one length.
        rows: Vec<Vec<f64>>,
    },
    /// Items a task rendered itself before this emitter existed, kept verbatim so that the
    /// committed bytes of the table do not move. The text ends with a newline.
    Source(String),
}

impl TableItem {
    /// The item's name, or `None` for [`TableItem::Source`].
    #[must_use]
    pub fn name(&self) -> Option<&str> {
        match self {
            Self::Scalar { name, .. }
            | Self::Array { name, .. }
            | Self::Tuples { name, .. }
            | Self::Structs { name, .. }
            | Self::Nested { name, .. } => Some(name),
            Self::Source(_) => None,
        }
    }

    /// Writes the item into `out`, ending with a newline.
    fn write(&self, out: &mut String) -> Result<(), EmitTableError> {
        match self {
            Self::Scalar { name, doc, value } => {
                write_doc(out, doc);
                let _ = writeln!(
                    out,
                    "pub const {name}: f64 = {};",
                    finite_literal(name, *value)?
                );
            }
            Self::Array { name, doc, values } => {
                let rows = values
                    .iter()
                    .map(|&v| finite_literal(name, v))
                    .collect::<Result<Vec<_>, _>>()?;
                let decl = format!("pub const {name}: [f64; {}]", values.len());
                write_array(out, doc, &decl, &rows);
            }
            Self::Tuples { name, doc, rows } => {
                let len = same_length(name, rows)?;
                if len < 2 {
                    return Err(EmitTableError::Ragged { item: name.clone() });
                }
                let ty = vec!["f64"; len].join(", ");
                let decl = format!("pub const {name}: [({ty}); {}]", rows.len());
                let rows = rows
                    .iter()
                    .map(|r| row(name, r).map(|r| format!("({r})")))
                    .collect::<Result<Vec<_>, _>>()?;
                write_array(out, doc, &decl, &rows);
            }
            Self::Structs {
                name,
                doc,
                type_name,
                fields,
                rows,
            } => {
                if rows.iter().any(|r| r.len() != fields.len()) {
                    return Err(EmitTableError::Ragged { item: name.clone() });
                }
                let decl = format!("pub const {name}: [{type_name}; {}]", rows.len());
                let rows = rows
                    .iter()
                    .map(|r| {
                        r.iter()
                            .zip(fields)
                            .map(|(&v, f)| finite_literal(name, v).map(|v| format!("{f}: {v}")))
                            .collect::<Result<Vec<_>, _>>()
                            .map(|values| format!("{type_name} {{ {} }}", values.join(", ")))
                    })
                    .collect::<Result<Vec<_>, _>>()?;
                write_array(out, doc, &decl, &rows);
            }
            Self::Nested { name, doc, rows } => {
                let len = same_length(name, rows)?;
                let decl = format!("pub const {name}: [[f64; {len}]; {}]", rows.len());
                let rows = rows
                    .iter()
                    .map(|r| row(name, r).map(|r| format!("[{r}]")))
                    .collect::<Result<Vec<_>, _>>()?;
                write_array(out, doc, &decl, &rows);
            }
            Self::Source(text) => out.push_str(text),
        }
        Ok(())
    }
}

/// Writes `doc` as `///` lines.
fn write_doc(out: &mut String, doc: &[String]) {
    for line in doc {
        if line.is_empty() {
            out.push_str("///\n");
        } else {
            let _ = writeln!(out, "/// {line}");
        }
    }
}

/// Writes an array item: its doc, `#[rustfmt::skip]`, the declaration `decl`, one row a line.
fn write_array(out: &mut String, doc: &[String], decl: &str, rows: &[String]) {
    write_doc(out, doc);
    let _ = writeln!(out, "#[rustfmt::skip]\n{decl} = [");
    for r in rows {
        let _ = writeln!(out, "    {r},");
    }
    out.push_str("];\n");
}

/// The literals of `values`, comma-separated.
fn row(name: &str, values: &[f64]) -> Result<String, EmitTableError> {
    values
        .iter()
        .map(|&v| finite_literal(name, v))
        .collect::<Result<Vec<_>, _>>()
        .map(|v| v.join(", "))
}

/// The common length of `rows`, or [`EmitTableError::Ragged`].
fn same_length(name: &str, rows: &[Vec<f64>]) -> Result<usize, EmitTableError> {
    let len = rows.first().map_or(0, Vec::len);
    if rows.iter().all(|r| r.len() == len) {
        Ok(len)
    } else {
        Err(EmitTableError::Ragged {
            item: name.to_owned(),
        })
    }
}

/// A table's contents: its module doc and its items. The [`Header`] is added when it is written.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RustTable {
    /// The one-sentence summary, one entry a line; it ends with a full stop.
    pub summary: Vec<String>,
    /// Paragraphs of notes after the header, one entry a line, an empty entry between paragraphs.
    pub notes: Vec<String>,
    /// The items, in the order they are written, a blank line between each.
    pub items: Vec<TableItem>,
}

impl RustTable {
    /// The names of the items, in order, [`TableItem::Source`] items left out.
    #[must_use]
    pub fn item_names(&self) -> Vec<&str> {
        self.items.iter().filter_map(TableItem::name).collect()
    }

    /// The body: the items, a blank line before each.
    ///
    /// # Errors
    ///
    /// [`EmitTableError::NonFinite`] for a value that is not finite, [`EmitTableError::Ragged`] for
    /// rows of differing lengths.
    pub fn body(&self) -> Result<String, EmitTableError> {
        let mut out = String::new();
        for item in &self.items {
            out.push('\n');
            item.write(&mut out)?;
        }
        Ok(out)
    }

    /// The whole file: the module doc with `header`, then the body.
    ///
    /// # Errors
    ///
    /// As [`body`](Self::body) and [`Header::lines`], and [`EmitTableError::Header`] if the
    /// summary is empty or does not end with a full stop.
    pub fn render(&self, header: &Header) -> Result<String, EmitTableError> {
        Ok(format!(
            "{}{}",
            self.header_comment("//!", header)?,
            self.body()?
        ))
    }

    /// The file's leading comment lines under `prefix` (`//!` for a file, `//` for a block).
    fn header_comment(&self, prefix: &str, header: &Header) -> Result<String, EmitTableError> {
        let ends = self.summary.last().is_some_and(|l| l.ends_with('.'));
        if !ends {
            return Err(EmitTableError::Header(
                "the summary is empty or has no full stop".to_owned(),
            ));
        }
        let mut out = String::new();
        let mut line = |text: &str| {
            if text.is_empty() {
                let _ = writeln!(out, "{prefix}");
            } else {
                let _ = writeln!(out, "{prefix} {text}");
            }
        };
        for l in &self.summary {
            line(l);
        }
        line("");
        for l in header.lines()? {
            line(&l);
        }
        if !self.notes.is_empty() {
            line("");
            for l in &self.notes {
                line(l);
            }
        }
        Ok(out)
    }

    /// One task's block of a shared file: its markers, its header in `//` comments, then its body.
    ///
    /// # Errors
    ///
    /// As [`render`](Self::render).
    pub fn render_block(&self, name: &str, header: &Header) -> Result<String, EmitTableError> {
        Ok(format!(
            "{BLOCK_BEGIN}{name}\n{}{}{BLOCK_END}{name}\n",
            self.header_comment("//", header)?,
            self.body()?
        ))
    }
}

/// A table file, or one task's block of it, split into its header and its body.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TableText {
    /// The header's key lines, comment prefixes removed.
    pub header_lines: Vec<String>,
    /// The body: everything after the leading comment lines (for a block, up to its end marker).
    pub body: String,
}

impl TableText {
    /// Splits a whole table file: the leading `//!` lines, then the body. A file whose leading
    /// comment has no header has no header lines, and [`header`](Self::header) fails.
    #[must_use]
    pub fn of_file(text: &str) -> Self {
        let (comment, body) = split_leading(text, "//!");
        Self {
            header_lines: key_lines(&comment),
            body: body.to_owned(),
        }
    }

    /// Splits task `name`'s block out of a shared file, or `None` if the file has no such block.
    ///
    /// # Errors
    ///
    /// [`EmitTableError::Header`] if the block has no end marker.
    pub fn of_block(text: &str, name: &str) -> Result<Option<Self>, EmitTableError> {
        let Some((_, inner, _)) = block_bounds(text, name)? else {
            return Ok(None);
        };
        let (comment, body) = split_leading(inner, "//");
        Ok(Some(Self {
            header_lines: key_lines(&comment),
            body: body.to_owned(),
        }))
    }

    /// The header read back.
    ///
    /// # Errors
    ///
    /// As [`Header::parse`].
    pub fn header(&self) -> Result<Header, EmitTableError> {
        Header::parse(self.header_lines.iter().map(String::as_str))
    }

    /// The SHA-256 of the body, in hex.
    #[must_use]
    pub fn body_sha256(&self) -> String {
        sha256_hex(self.body.as_bytes())
    }
}

/// The comment lines under `prefix` that open `text` (prefix and one space removed), and the rest.
fn split_leading<'a>(text: &'a str, prefix: &str) -> (Vec<&'a str>, &'a str) {
    let mut lines = Vec::new();
    let mut rest = text;
    while let Some(line_end) = rest.find('\n') {
        let line = &rest[..line_end];
        let Some(stripped) = line.strip_prefix(prefix) else {
            break;
        };
        // `//` also matches `///` and `//!`, which are never header lines.
        if stripped.starts_with('/') || stripped.starts_with('!') {
            break;
        }
        lines.push(stripped.strip_prefix(' ').unwrap_or(stripped));
        rest = &rest[line_end + 1..];
    }
    (lines, rest)
}

/// The header's key lines within a leading comment: from the `@` line to the next blank line, or
/// none if the comment has no `@` line (a table written before this grammar existed).
fn key_lines(comment: &[&str]) -> Vec<String> {
    comment
        .iter()
        .skip_while(|l| !l.starts_with('@'))
        .take_while(|l| !l.is_empty())
        .map(|&l| l.to_owned())
        .collect()
}

/// Where task `name`'s block lies in `text`: the byte range of the whole block including both
/// markers and the end marker's newline, and the text between the markers.
fn block_bounds<'a>(
    text: &'a str,
    name: &str,
) -> Result<Option<(usize, &'a str, usize)>, EmitTableError> {
    let begin = format!("{BLOCK_BEGIN}{name}\n");
    let end = format!("{BLOCK_END}{name}\n");
    let Some(start) = text.find(&begin) else {
        return Ok(None);
    };
    let inner_start = start + begin.len();
    let inner_len = text[inner_start..]
        .find(&end)
        .ok_or_else(|| EmitTableError::Header(format!("the block `{name}` has no end marker")))?;
    let inner = &text[inner_start..inner_start + inner_len];
    Ok(Some((start, inner, inner_start + inner_len + end.len())))
}

/// How a task's table sits in its file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Placement {
    /// The task owns the whole file.
    File,
    /// The task shares the file and owns one block of it, between its markers.
    Block,
}

/// The paths the emitter and the staleness check work on: normally the repository's, in tests a
/// temporary directory.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Workspace {
    /// The sim's `src/tables/` directory.
    pub tables_dir: PathBuf,
    /// The fitting crate's `manifests/` directory.
    pub manifests_dir: PathBuf,
    /// The fitting crate's `data/` directory.
    pub data_dir: PathBuf,
    /// The fitting crate's `tables.lock`.
    pub lock_path: PathBuf,
}

impl Workspace {
    /// The repository's own paths, fixed at compile time so that the tool works from any
    /// directory.
    #[must_use]
    pub fn repository() -> Self {
        let fit = Path::new(env!("CARGO_MANIFEST_DIR"));
        Self {
            tables_dir: fit.join("../hyperion-sim/src/tables"),
            manifests_dir: fit.join("manifests"),
            data_dir: fit.join("data"),
            lock_path: fit.join("tables.lock"),
        }
    }

    /// A workspace laid out under `root` as the repository is: `tables/`, `manifests/`, `data/`
    /// and `tables.lock`.
    #[must_use]
    pub fn under(root: &Path) -> Self {
        Self {
            tables_dir: root.join("tables"),
            manifests_dir: root.join("manifests"),
            data_dir: root.join("data"),
            lock_path: root.join("tables.lock"),
        }
    }

    /// The sim's `tables/mod.rs`, which holds `MANIFEST`.
    #[must_use]
    pub fn tables_mod(&self) -> PathBuf {
        self.tables_dir.join("mod.rs")
    }
}

/// A table ready to be written: its contents, its header less `since-generator-version`, and where
/// it goes.
#[derive(Debug, Clone, PartialEq)]
pub struct Emission<'a> {
    /// The task's name, which is the table's name in the lock file and `MANIFEST`.
    pub name: &'a str,
    /// The table's file, relative to the sim's `tables/`.
    pub table_path: &'a str,
    /// Whether the task owns the file or a block of it.
    pub placement: Placement,
    /// The contents.
    pub table: &'a RustTable,
    /// The header; its `since_generator_version` is set by [`write_table`].
    pub header: Header,
    /// The fingerprint's probe values, for the lock file.
    pub fingerprint: Vec<f64>,
}

/// Renders `emission` as it would stand in the file at `since`: the whole file, or the block.
///
/// # Errors
///
/// As [`RustTable::render`].
pub fn render_emission(emission: &Emission<'_>, since: u32) -> Result<String, EmitTableError> {
    let mut header = emission.header.clone();
    header.since_generator_version = Some(since);
    match emission.placement {
        Placement::File => emission.table.render(&header),
        Placement::Block => emission.table.render_block(emission.name, &header),
    }
}

/// Where [`write_table`] writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Destination<'a> {
    /// Into the workspace's tables, updating its lock file and `MANIFEST`, with `--since`, which
    /// must equal the sim's current generator version.
    Tables {
        /// The paths.
        workspace: &'a Workspace,
        /// The `--since` given, if any.
        since: Option<u32>,
        /// The sim's `GENERATOR_VERSION`.
        current: u32,
    },
    /// To a file elsewhere (`--out`), touching nothing else. The header's
    /// `since-generator-version` is the current version.
    Out {
        /// The file.
        path: &'a Path,
        /// The sim's `GENERATOR_VERSION`.
        current: u32,
    },
}

/// The file an emission lands in, and whether its bytes changed.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Written {
    /// The file written.
    pub path: PathBuf,
    /// The `since-generator-version` in its header.
    pub since: u32,
    /// Whether the table's body differs from what was there before.
    pub body_changed: bool,
}

/// What writing an emission into the tables would do, worked out without writing anything.
#[derive(Debug, Clone, PartialEq)]
pub struct PlannedWrite {
    /// The file.
    pub path: PathBuf,
    /// The file's whole new text.
    pub text: String,
    /// The `since-generator-version` in the table's header.
    pub since: u32,
    /// Whether the table's body differs from what was there before.
    pub body_changed: bool,
    /// The table's lock-file entry.
    pub entry: LockEntry,
}

/// Works out what writing `emission` into `workspace`'s tables with `--since` would do, with the
/// guards of Design note 10, and writes nothing.
///
/// `--since` must be given and equal the current generator version. If the body is byte-identical
/// to the committed one, the table keeps its old `since-generator-version`: a fit that changes
/// nothing needs no bump. If it differs while `--since` equals the old table's value, the write is
/// refused, since a changed table needs a bumped generator version.
///
/// # Errors
///
/// [`EmitTableError::SinceRequired`], [`EmitTableError::SinceNotCurrent`] and
/// [`EmitTableError::ChangedBodyWithoutNewSince`] for the guards; [`EmitTableError::Io`] if the
/// committed table cannot be read; the rendering's errors.
pub fn plan_write(
    emission: &Emission<'_>,
    workspace: &Workspace,
    since: Option<u32>,
    current: u32,
) -> Result<PlannedWrite, EmitTableError> {
    let since = since.ok_or(EmitTableError::SinceRequired)?;
    if since != current {
        return Err(EmitTableError::SinceNotCurrent { since, current });
    }
    let path = workspace.tables_dir.join(emission.table_path);
    let old_text = match fs::read_to_string(&path) {
        Ok(text) => Some(text),
        Err(e) if e.kind() == io::ErrorKind::NotFound => None,
        Err(source) => return Err(EmitTableError::Io { path, source }),
    };
    let old = match (&old_text, emission.placement) {
        (None, _) => None,
        (Some(text), Placement::File) => Some(TableText::of_file(text)),
        (Some(text), Placement::Block) => TableText::of_block(text, emission.name)?,
    };
    let body = emission.table.body()?;
    // A table written before the header grammar has no `since` to keep or compare; it takes the
    // current version, which is what its move into the grammar records.
    let old_since = |old: &TableText| {
        old.header()
            .ok()
            .and_then(|header| header.since_generator_version)
    };
    let (since, body_changed) = match &old {
        Some(old) if old.body == body => (old_since(old).unwrap_or(since), false),
        Some(old) => {
            if old_since(old) == Some(since) {
                return Err(EmitTableError::ChangedBodyWithoutNewSince {
                    table: emission.name.to_owned(),
                    since,
                });
            }
            (since, true)
        }
        None => (since, true),
    };
    let rendered = render_emission(emission, since)?;
    let text = match (emission.placement, old_text) {
        (Placement::File, _) | (Placement::Block, None) => rendered,
        (Placement::Block, Some(existing)) => replace_block(&existing, emission.name, &rendered)?,
    };
    let entry = LockEntry {
        name: emission.name.to_owned(),
        path: emission.table_path.to_owned(),
        task: emission.header.task.clone(),
        revision: emission.header.revision.unwrap_or_default(),
        inputs_sha256: emission.header.inputs_sha256.clone(),
        body_sha256: sha256_hex(body.as_bytes()),
        fingerprint: emission.fingerprint.clone(),
        since_generator_version: since,
        provisional: matches!(emission.header.kind, Some(HeaderKind::Provisional { .. })),
        acceptance: emission.header.acceptance.clone(),
    };
    Ok(PlannedWrite {
        path,
        text,
        since,
        body_changed,
        entry,
    })
}

/// Writes `emission` to `destination`.
///
/// Into the tables, by [`plan_write`]'s rules, then rewriting the table's lock-file entry and the
/// sim's `MANIFEST` to match. With `--out`, to that file alone, the header's
/// `since-generator-version` the current version.
///
/// # Errors
///
/// As [`plan_write`]; [`EmitTableError::Io`] and [`EmitTableError::Lock`] for a file that cannot
/// be read or written.
pub fn write_table(
    emission: &Emission<'_>,
    destination: Destination<'_>,
) -> Result<Written, EmitTableError> {
    match destination {
        Destination::Out { path, current } => {
            let text = render_emission(emission, current)?;
            write(path, &text)?;
            Ok(Written {
                path: path.to_owned(),
                since: current,
                body_changed: true,
            })
        }
        Destination::Tables {
            workspace,
            since,
            current,
        } => {
            let planned = plan_write(emission, workspace, since, current)?;
            write(&planned.path, &planned.text)?;
            let mut lock = LockFile::read(&workspace.lock_path)?;
            lock.upsert(planned.entry);
            lock.write(&workspace.lock_path)?;
            write_manifest(workspace, &lock)?;
            Ok(Written {
                path: planned.path,
                since: planned.since,
                body_changed: planned.body_changed,
            })
        }
    }
}

/// `existing` with task `name`'s block replaced by `block`, or `block` appended after a blank line
/// if the file has none.
fn replace_block(existing: &str, name: &str, block: &str) -> Result<String, EmitTableError> {
    Ok(match block_bounds(existing, name)? {
        Some((start, _, end)) => format!("{}{block}{}", &existing[..start], &existing[end..]),
        None => format!("{existing}\n{block}"),
    })
}

/// Writes `text` to `path`.
fn write(path: &Path, text: &str) -> Result<(), EmitTableError> {
    fs::write(path, text).map_err(|source| EmitTableError::Io {
        path: path.to_owned(),
        source,
    })
}

/// The Rust source of `tables::MANIFEST` for `lock`'s entries, markers included.
#[must_use]
pub fn manifest_source(lock: &LockFile) -> String {
    if lock.entries().is_empty() {
        return format!(
            "{MANIFEST_BEGIN}\npub const MANIFEST: &[TableInfo] = &[];\n{MANIFEST_END}\n"
        );
    }
    let mut out = format!("{MANIFEST_BEGIN}\npub const MANIFEST: &[TableInfo] = &[\n");
    for entry in lock.entries() {
        let _ = writeln!(
            out,
            "    TableInfo {{\n        name: \"{}\",\n        revision: {},\n        \
             since_generator_version: {},\n        provisional: {},\n    }},",
            entry.name, entry.revision, entry.since_generator_version, entry.provisional
        );
    }
    let _ = writeln!(out, "];\n{MANIFEST_END}");
    out
}

/// Rewrites `tables::MANIFEST` between its markers in the workspace's `tables/mod.rs`.
///
/// # Errors
///
/// [`EmitTableError::Io`] if the file cannot be read or written, [`EmitTableError::Header`] if it
/// has no markers.
pub fn write_manifest(workspace: &Workspace, lock: &LockFile) -> Result<(), EmitTableError> {
    let path = workspace.tables_mod();
    let text = fs::read_to_string(&path).map_err(|source| EmitTableError::Io {
        path: path.clone(),
        source,
    })?;
    let no_markers =
        || EmitTableError::Header(format!("{} has no MANIFEST markers", path.display()));
    let start = text.find(MANIFEST_BEGIN).ok_or_else(no_markers)?;
    let end_marker = text[start..].find(MANIFEST_END).ok_or_else(no_markers)? + start;
    let end = end_marker + MANIFEST_END.len() + usize::from(text[end_marker..].contains('\n'));
    let fresh = format!(
        "{}{}{}",
        &text[..start],
        manifest_source(lock),
        &text[end..]
    );
    if fresh != text {
        write(&path, &fresh)?;
    }
    Ok(())
}

/// A table could not be emitted.
#[derive(Debug, thiserror::Error)]
pub enum EmitTableError {
    /// A value of the item is NaN or infinite.
    #[error("item `{item}` holds a value that is not finite")]
    NonFinite {
        /// The item.
        item: String,
    },
    /// The rows of an item differ in length, or a tuple has fewer than two values.
    #[error("the rows of item `{item}` differ in length")]
    Ragged {
        /// The item.
        item: String,
    },
    /// A header is incomplete or not in the grammar; the text says how.
    #[error("{0}")]
    Header(String),
    /// Writing into the sim's tables needs `--since`.
    #[error("writing into the sim's tables needs `--since <generator version>`")]
    SinceRequired,
    /// `--since` is not the sim's current generator version.
    #[error("`--since {since}` is not the current generator version, {current}")]
    SinceNotCurrent {
        /// The version given.
        since: u32,
        /// `GENERATOR_VERSION`.
        current: u32,
    },
    /// The table's body changed, but `--since` equals the old table's: bump the generator version.
    #[error(
        "table `{table}` changed but keeps since-generator-version {since}: bump GENERATOR_VERSION \
         and pass the new version to `--since`"
    )]
    ChangedBodyWithoutNewSince {
        /// The table.
        table: String,
        /// The unchanged version.
        since: u32,
    },
    /// A file could not be read or written.
    #[error("cannot read or write {}", path.display())]
    Io {
        /// The file.
        path: PathBuf,
        /// Why.
        source: io::Error,
    },
    /// The lock file could not be read or written.
    #[error(transparent)]
    Lock(#[from] ReadLockError),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn literals_read_back_to_the_same_value_and_are_grouped() {
        for (value, expected) in [
            (0.04, "0.04"),
            (3.5, "3.5"),
            (1.0, "1.0"),
            (0.0, "0.0"),
            (1_234.567_8, "1_234.567_8"),
            (0.001_234_567_891_234_5, "0.001_234_567_891_234_5"),
            (1.234_567e-7, "1.234_567e-7"),
            (-5.868_123_4, "-5.868_123_4"),
            (-123.5, "-123.5"),
            (-1_234.5, "-1_234.5"),
            (-2.5e-9, "-2.5e-9"),
        ] {
            let text = literal(value);
            assert_eq!(text, expected);
            let back: f64 = text.replace('_', "").parse().unwrap();
            assert!(back.total_cmp(&value).is_eq(), "{text}");
        }
    }

    /// 10⁴ values across the whole range, subnormals and powers of ten among them, each written,
    /// stripped of its separators, read back and compared bit for bit.
    #[test]
    fn emitted_literals_round_trip() {
        let mut values = vec![
            f64::MIN_POSITIVE,
            f64::MIN_POSITIVE / 2.0,
            5e-324,
            -5e-324,
            f64::MAX,
            f64::MIN,
            f64::EPSILON,
            -0.0,
        ];
        values.extend((-300..=300).map(|e| format!("1e{e}").parse::<f64>().unwrap()));
        let mut state: u64 = 0x9e37_79b9_7f4a_7c15;
        while values.len() < 10_000 {
            // SplitMix64, then a float from sign, exponent and mantissa bits, so every binade is
            // reached, subnormals included.
            state = state.wrapping_add(0x9e37_79b9_7f4a_7c15);
            let mut z = state;
            z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
            z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
            z ^= z >> 31;
            let v = f64::from_bits(z);
            if v.is_finite() {
                values.push(v);
            }
        }
        for v in values {
            let text = literal(v);
            let (sign, digits) = text.strip_prefix('-').map_or(("", &*text), |d| ("-", d));
            assert!(!digits.starts_with('_') && !digits.contains("__"), "{text}");
            let back: f64 = format!("{sign}{}", digits.replace('_', ""))
                .parse()
                .unwrap();
            assert!(back.total_cmp(&v).is_eq(), "{v:?} came back as {back:?}");
        }
    }

    fn toy_table() -> RustTable {
        RustTable {
            summary: vec!["A toy table.".to_owned()],
            notes: vec!["Its notes.".to_owned()],
            items: vec![
                TableItem::Scalar {
                    name: "SCALE".to_owned(),
                    doc: vec!["A scale.".to_owned()],
                    value: 0.68,
                },
                TableItem::Array {
                    name: "NODES".to_owned(),
                    doc: vec!["Nodes.".to_owned()],
                    values: vec![1.0, 1.5e-9, 12_345.678],
                },
                TableItem::Tuples {
                    name: "PAIRS".to_owned(),
                    doc: vec!["Pairs.".to_owned()],
                    rows: vec![vec![1.0, 2.0], vec![3.0, 4.0]],
                },
                TableItem::Structs {
                    name: "TERMS".to_owned(),
                    doc: vec!["Terms.".to_owned()],
                    type_name: "Term".to_owned(),
                    fields: vec!["weight".to_owned(), "width".to_owned()],
                    rows: vec![vec![0.5, 0.25]],
                },
                TableItem::Nested {
                    name: "GRID".to_owned(),
                    doc: vec!["A grid.".to_owned()],
                    rows: vec![vec![1.0, 2.0], vec![3.0, 4.0]],
                },
            ],
        }
    }

    fn toy_header() -> Header {
        Header {
            kind: Some(HeaderKind::Generated),
            task: Some("toy".to_owned()),
            revision: Some(3),
            tool_version: None,
            inputs_sha256: Some("a".repeat(64)),
            manifest: Some("crates/hyperion-fit/manifests/toy.toml".to_owned()),
            data: Some(vec![("census".to_owned(), "0123456789ab".to_owned())]),
            sim_fingerprint: Some(None),
            since_generator_version: Some(11),
            source: Some(
                "a source whose citation runs long enough that it must continue onto a second \
                 line of the header, as long citations do"
                    .to_owned(),
            ),
            acceptance: Some("within 1%".to_owned()),
        }
    }

    #[test]
    fn emitted_file_passes_header_grammar() {
        let text = toy_table().render(&toy_header()).unwrap();
        let lines: Vec<&str> = text.lines().collect();
        assert_eq!(lines[0], "//! A toy table.");
        assert_eq!(lines[1], "//!");
        assert_eq!(
            lines[2],
            format!(
                "//! @generated by hyperion-fit {}, task `toy` revision 3. Do not edit.",
                env!("CARGO_PKG_VERSION")
            )
        );
        for (line, key) in lines[3..].iter().zip([
            "inputs-sha256: ",
            "manifest: ",
            "data: `census@0123456789ab`",
            "sim-fingerprint: none",
            "since-generator-version: 11",
            "source: ",
            "  ",
            "acceptance: within 1%",
        ]) {
            assert!(line.starts_with(&format!("//! {key}")), "{line}");
        }
        assert!(lines.iter().all(|l| l.chars().count() <= 100), "{text}");
        let split = TableText::of_file(&text);
        let mut header = toy_header();
        header.tool_version = Some(env!("CARGO_PKG_VERSION").to_owned());
        assert_eq!(split.header().unwrap(), header);
        assert_eq!(split.body, toy_table().body().unwrap());
        assert!(text.contains("#[rustfmt::skip]\npub const NODES: [f64; 3] = [\n    1.0,\n"));
        assert!(text.contains("    1.5e-9,\n    12_345.678,\n];\n"));
        assert!(text.contains("pub const PAIRS: [(f64, f64); 2] = [\n    (1.0, 2.0),\n"));
        assert!(
            text.contains(
                "pub const TERMS: [Term; 1] = [\n    Term { weight: 0.5, width: 0.25 },\n"
            )
        );
        assert!(text.contains("pub const GRID: [[f64; 2]; 2] = [\n    [1.0, 2.0],\n"));
        assert!(text.contains("\n/// A scale.\npub const SCALE: f64 = 0.68;\n"));
        assert_eq!(
            toy_table().item_names(),
            ["SCALE", "NODES", "PAIRS", "TERMS", "GRID"]
        );
    }

    #[test]
    fn a_provisional_header_needs_only_its_since_and_source() {
        let header = Header {
            kind: Some(HeaderKind::Provisional {
                by: "P15.T4.a".to_owned(),
            }),
            since_generator_version: Some(11),
            source: Some("plan 02".to_owned()),
            ..Header::default()
        };
        let lines = header.lines().unwrap();
        assert_eq!(
            lines,
            [
                "@provisional by P15.T4.a. Do not edit.",
                "since-generator-version: 11",
                "source: plan 02"
            ]
        );
        assert_eq!(
            Header::parse(lines.iter().map(String::as_str)).unwrap(),
            header
        );
        let mut by_task = toy_header();
        by_task.kind = Some(HeaderKind::Provisional {
            by: "P06.T19.b".to_owned(),
        });
        by_task.tool_version = Some("0.1.0".to_owned());
        let lines = by_task.lines().unwrap();
        assert_eq!(
            lines[0],
            "@provisional by hyperion-fit 0.1.0, task `toy` revision 3 (P06.T19.b). Do not edit."
        );
        assert_eq!(
            Header::parse(lines.iter().map(String::as_str)).unwrap(),
            by_task
        );
    }

    #[test]
    fn a_header_out_of_grammar_is_refused() {
        for lines in [
            vec!["@generated by hyperion-fit 0.1.0, task `toy` revision 3. Do not edit."],
            vec!["generated by me"],
            vec![
                "@provisional by P15.T4.a. Do not edit.",
                "since-generator-version: 11",
                "since-generator-version: 12",
                "source: x",
            ],
            vec![
                "@provisional by P15.T4.a. Do not edit.",
                "since-generator-version: eleven",
                "source: x",
            ],
            vec![
                "@provisional by P15.T4.a. Do not edit.",
                "colour: blue",
                "since-generator-version: 11",
                "source: x",
            ],
        ] {
            assert!(
                matches!(Header::parse(lines.clone()), Err(EmitTableError::Header(_))),
                "{lines:?}"
            );
        }
    }

    #[test]
    fn a_value_that_is_not_finite_is_refused() {
        let table = RustTable {
            summary: vec!["A table.".to_owned()],
            notes: Vec::new(),
            items: vec![TableItem::Array {
                name: "BAD".to_owned(),
                doc: Vec::new(),
                values: vec![1.0, f64::NAN],
            }],
        };
        match table.render(&toy_header()) {
            Err(EmitTableError::NonFinite { item }) => assert_eq!(item, "BAD"),
            other => panic!("{other:?}"),
        }
    }

    #[test]
    fn a_verbatim_body_is_kept_byte_for_byte() {
        let committed = "//! Old.\n//!\n//! @static.\n\n/// X.\npub const X: f64 = 1.0;\n";
        let split = TableText::of_file(committed);
        assert_eq!(split.body, "\n/// X.\npub const X: f64 = 1.0;\n");
        let table = RustTable {
            summary: vec!["New.".to_owned()],
            notes: Vec::new(),
            items: vec![TableItem::Source(split.body[1..].to_owned())],
        };
        assert_eq!(table.body().unwrap(), split.body);
    }
}
