//! The kick law's provisional rank table (plan 06, P06.T19.b): the 257 quantiles of Mandel and
//! Müller's ordinary kick score over the reference population, which
//! `hyperion_sim::stellar::remnant::KickRankTable` interpolates.
//!
//! This is the provisional table P06.T19.b commits, made by the sim's own
//! [`score_quantiles`] with 10⁶ scores. Plan 15's P15.T5.a takes the task over, runs the same
//! function with 10⁷ and replaces the file (P06.T19.e). It builds a full track for every sample
//! star, some 1.7 million massive stars at about a millisecond each, so it takes half an hour or
//! more; its test runs it on a small sample.

use std::fmt::Write as _;

use hyperion_sim::Seed;
use hyperion_sim::stellar::remnant::KickLawParams;
use hyperion_sim::stellar::remnant::reference::{
    KROUPA_HIGH_MASS_SLOPE, MASS_RANGE, QUANTILES, ReferencePopulation, score_quantiles,
};
use hyperion_sim::tables::kick_rank;

use super::render::literal;

/// The scores the committed table is made from: 10⁶ (P06.T19.b).
pub const DRAWS: u64 = 1_000_000;

/// The seed of the committed table's sample.
pub const SEED: u64 = 0x0619_b000_0000_0000;

/// The fitted table: the quantiles and what they were made from.
#[derive(Debug, Clone, PartialEq)]
pub struct KickRankFit {
    /// The score's quantiles at ranks i ÷ 256.
    pub quantiles: [f64; QUANTILES],
    /// The number of scores.
    pub draws: u64,
    /// The sample's seed.
    pub seed: u64,
}

/// The committed table's fit: [`DRAWS`] scores under [`SEED`].
#[must_use]
pub fn fit() -> KickRankFit {
    fit_with(DRAWS, SEED)
}

/// The quantiles of `draws` scores of the reference population under `seed`.
///
/// # Panics
///
/// If `draws` is below 2.
#[must_use]
pub fn fit_with(draws: u64, seed: u64) -> KickRankFit {
    let population = ReferencePopulation::default();
    KickRankFit {
        quantiles: score_quantiles(&population, draws, Seed::new(seed)),
        draws,
        seed,
    }
}

/// The table as the Rust source of `hyperion-sim/src/tables/kick_rank.rs`.
#[must_use]
pub fn render(fit: &KickRankFit) -> String {
    let params = KickLawParams::default();
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! The kick law's rank table and its four defaults (plan 06, P06.T19.b): the quantiles of\n\
         //! Mandel and Müller's ordinary kick score over the reference population, which\n\
         //! `stellar::remnant::KickRankTable` interpolates, and the constants\n\
         //! `stellar::remnant::KickLawParams::default` reads.\n\
         //!\n\
         //! **Provisional** (P06.T19.b): plan 15's P15.T5.a replaces the quantiles with a run of 10⁷\n\
         //! scores and takes the file over, with a generator-version bump (P06.T19.e).\n\
         //!\n\
         //! Generated by `hyperion-fit run kick_rank`, version 0. Do not edit.\n\
         //!\n\
         //! Inputs: `stellar::remnant::reference::score_quantiles` over {draws} scores of seed\n\
         //! {seed:#018x}: Kroupa primaries of {lo}–{hi} M☉ (slope {slope}) at Z = 0.02 on the\n\
         //! generator's tracks, the iron-core collapses of single and wind-stripped progenitors that\n\
         //! leave a neutron star, each scored (`M_CO` − `M_rem`) ÷ `M_rem` × ξ with ξ normal about 1 of\n\
         //! relative scatter {scatter} redrawn until positive.",
        draws = fit.draws,
        seed = fit.seed,
        lo = MASS_RANGE.0,
        hi = MASS_RANGE.1,
        slope = KROUPA_HIGH_MASS_SLOPE,
        scatter = params.score_scatter,
    );
    out.push('\n');
    out.push_str(
        "/// The ordinary kick score at ranks i ÷ 256 over the reference population, strictly\n\
         /// increasing.\n",
    );
    let _ = writeln!(out, "pub const SCORE_QUANTILES: [f64; {QUANTILES}] = [");
    for q in fit.quantiles {
        let _ = writeln!(out, "    {},", literal(q));
    }
    out.push_str("];\n\n");
    let (lo, hi) = kick_rank::LOW_RAMP;
    let _ = writeln!(
        out,
        "/// The carbon–oxygen cores, M☉, over which a companion-stripped progenitor's chance of the\n\
         /// low kick mode falls from 1 to 0 (the brainstorm's \"Open questions\").\n\
         pub const LOW_RAMP: (f64, f64) = ({}, {});\n\n\
         /// The factor on a black hole's ordinary kick: a HYPERION default (Mandel and Müller 2020\n\
         /// have 0.5).\n\
         pub const BH_FACTOR: f64 = {};\n\n\
         /// The single star's electron-capture window, M☉ of the mass `m_c_bagb` reads (the\n\
         /// brainstorm's 0.1; ruling 45.1).\n\
         pub const EC_WINDOW_SINGLE: f64 = {};\n\n\
         /// A companion-stripped star's electron-capture window, M☉ of the same mass (the\n\
         /// brainstorm's \"about 1\").\n\
         pub const EC_WINDOW_STRIPPED: f64 = {};",
        literal(lo),
        literal(hi),
        literal(kick_rank::BH_FACTOR),
        literal(kick_rank::EC_WINDOW_SINGLE),
        literal(kick_rank::EC_WINDOW_STRIPPED),
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed file is this task's rendering of its own quantiles, byte for byte. The fit
    /// itself takes a quarter of an hour, so it is not rerun here; the sim's slow test
    /// `ranks_of_fresh_reference_scores_are_uniform` checks the table against fresh scores.
    #[test]
    fn the_committed_table_is_the_rendering_of_its_quantiles() {
        let committed = include_str!("../../../hyperion-sim/src/tables/kick_rank.rs");
        let fit = KickRankFit {
            quantiles: kick_rank::SCORE_QUANTILES,
            draws: DRAWS,
            seed: SEED,
        };
        assert_eq!(render(&fit), committed);
    }

    #[test]
    fn a_small_fit_is_strictly_increasing_and_repeats_bit_for_bit() {
        let a = fit_with(200, SEED);
        let b = fit_with(200, SEED);
        assert_eq!(a, b);
        assert!(a.quantiles.windows(2).all(|q| q[0] < q[1]));
        assert!(
            a.quantiles[0] > 0.0,
            "a neutron star's core outweighs it: {}",
            a.quantiles[0]
        );
        let source = render(&a);
        assert!(source.contains("pub const SCORE_QUANTILES: [f64; 257] = ["));
        assert!(source.contains("Provisional"));
        assert!(source.contains("200 scores of seed"));
        assert!(source.contains("0x0619b00000000000"));
        assert_eq!(source.matches(",\n").count(), QUANTILES);
    }
}
